server:
  port: $PORT
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testEmailForApp77@gmail.com
    password: 12345test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baselineOnMigrate: true
  datasource:
    url: jdbc:postgresql://ec2-52-48-159-67.eu-west-1.compute.amazonaws.com:5432/df5u6m8po2frq0?currentSchema=dfschema&sslmode=require
    username: hrzntorvvlbxkd
    password: ed3c757378324f26b77ae0e9aac73bd45c1125ae310d69a923265d5b65c897b9
  jpa:
    show-sql: true
    format_sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection pool_size: 10
---
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005












