spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/dfschema?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 77Light78MySQL79
  jpa:
    show-sql: true
    format_sql: true
    hibernate.ddl-auto: create
    hibernate.use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection pool_size: 10
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005











