spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dfschema?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 77Light78MySQL79
  server:
      port: 8080
  jpa:
    database: dfschema
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      connection pool_size: 10

