spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dfschema?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 77Light78MySQL79
  server:
    port: 3306
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection pool_size: 10
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  authorization:
    result: false
    user:
      id: 576
      name: Дмитрий Петров
      photo: /avatars/ab/cd/ef/52461.jpg
      email: petrov@petroff.ru
      moderation: false
      moderationCount: 0
      settings: false
posts:
  count: 10
  countWithTag: 10
  query: Java
  offset: 0
  limit: 10
  mode: recent
postsList:
  - firstPost:
      key: value
  - secondPost:
      key: value











